### ISSUE TITLE
Using HTTPS instead of HTTP 

### ISSUE THREAD

**Issue by jaDEVirek** [TomaszZiola/shorten_links_app#1]
There is an ambiguity in the current api:
 The problem is in handling secure link's address: **https** instead of **http**. 
` String[] schemes = {"https"};
        UrlValidator urlValidator = new UrlValidator(schemes);`
If you are using https secure URL, you should check SSL for actual host ( or just add a access ). However, If you decide to use https too, it's probably good solution to use : multicast.

sources: https://www.thomasvitale.com/https-spring-boot-ssl-certificate/
https://www.baeldung.com/java-broadcast-multicast
### Example: 
```java
    String[] schemes = {"http","https"}.
    UrlValidator urlValidator = new UrlValidator(schemes);
    if (urlValidator.isValid("ftp://foo.bar.com/")) {
       System.out.println("url is valid");
    } else {
       System.out.println("url is invalid");
    }
```
Other problem: all neccessary VALIDATION, should be placed in service layer, not in controller. 
Don't put this validation in the controller - controllers part is only be entry points for coming requests and exposing API's.

**Comment by TomaszZiola** [comment]
fixed
